- name: BE
  description: Backend work
  color: 4395f2
- name: bug
  description: Something isn't working
  color: ff0000
- name: chore
  description: A non issue related ticket
  color: 3d3937
- name: cooldown
  description: Something to work on between cycles
  color: afc6f2
  - name: Design
  description: Needs Design Input
  color: 9d63fc
- name: FE
  description: Frontend work
  color: f9980d
- name: feature
  description: The fun stuff
  color: c5def5
- name: 🏔∴
  description: Above tree line
  color: ffffff
- name: 🌲∴
  description: Below tree line
  color: ffffff
- name: dependencies
  description: Dependabot pull requests that update a package
  color: 0366d6
- name: javascript
  description: Dependabot pull requests that update Javascript code
  color: 168700
- name: cycle 07.11 - 07.22
  description: Short Cycle
  color: 9d03fc
