- name: 🧱BE
  description: Backend work
  color: 4395f2
- name: bug
  description: Something isn't working
  color: ff0000
- name: chore
  description: A non issue related ticket
  color: 3d3937
- name: cooldown
  description: Something to work on between cycles
  color: afc6f2
- name: 🌻FE
  description: Frontend work
  color: f9980d
- name: feature
  description: The fun stuff
  color: c5def5
- name: 🏔∴
  description: Above tree line
  color: ffffff
- name: 🌲∴
  description: Below tree line
  color: ffffff
- name: dependencies
  description: Dependabot pull requests that update a package
  color: 0366d6
- name: javascript
  description: Dependabot pull requests that update Javascript code
  color: 168700
- name: 🔥 bug p1
  description: Highest Priority Bug
  color: e50000
- name: 🤕 bug p2
  description: Medium Priority Bug
  color: cc0000
- name: 🐌 bug p3
  description: Low Priority Bug
  color: b20000
- name: 🎨Design
  description: Design Task
  color: e99695
- name: 🔬Product
  description: Product Task
  color: B8F793
- name: 🎨Design
  description: Design Task
  color: e99695