- name: BE
  description: Backend work
  color: 4395f2
- name: bug
  description: Something isn't working
  color: ff0000
- name: chore
  description: A non issue related ticket
  color: 3d3937
- name: cooldown
  description: Something to work on between cycles
  color: afc6f2

- name: 'cycle: 03.29 - 05.07'
  description: ''
  color: d08f45
- name: 'cycle: 05.24 - 06.18'
  description: ''
  color: d93f0b
- name: 'cycle: 06.28 - 07.23'
  description: ''
  color: 7ebe3e
- name: 'cycle: 08.02 - 08.27'
  description: ''
  color: 5e614b

- name: FE
  description: Frontend work
  color: f9980d
- name: feature
  description: The fun stuff
  color: c5def5
- name: 🏔∴
  description: Above tree line
  color: ffffff
- name: 🌲∴
  description: Below tree line
  color: ffffff

- name: dependencies
  description: Dependabot pull requests that update a package
  color: 0366d6
- name: javascript
  description: Dependabot pull requests that update Javascript code
  color: 168700
