- name: 🧱 BE
  description: Backend work
  color: 4395f2
  color: ff0000
- name: 🧹 chore
  description: A non issue related ticket
  color: 3d3937
- name: 🧊 cooldown
  description: Something to work on between cycles
  color: afc6f2
- name: 🌻 FE
  description: Frontend work
  color: f9980d
- name: 🎥 feature
  description: The fun stuff
  color: c5def5
- name: 🔥 p1 bug
  description: Highest Priority Bug
  color: e50000
- name: 🤕 p2 bug
  description: Medium Priority Bug
  color: cc0000
- name: 🐌 p3 bug
  description: Low Priority Bug
  color: b20000
- name: 🎨 Design
  description: Design Task
  color: e99695
- name: ⌛ hotRequest
  description: Hot Request - a request out of cycle work
  color: FD49B5
- name: ❓ Question
  description: Hot Request - a request out of cycle work
  color: FD49B5
- name: 📚 Documentation
  description: Documentation Task
  color: B8B799
- name: 📦 Release
  description: Release Task
  color: 6C4675
- name: 📝 Needs QA
  description: Review Task
  color: 9B111E
- name: 📅 Schedule
  description: Schedule Task
  color: 2A6478
- name: 📋 Planning
  description: Planning Task
  color: 063971
- name: 📌 Priority
  description: Priority Task
  color: E63244
- name: 📐 Architecture
  description: Architecture Task
  color: 4C9141
- name: 🦐 small batch
  description: Small Batch
  color: A98307
- name: 🐋 big batch
  description: Big Batch
  color: 317F43
- name: dependencies
  description: Dependency Task
  color: 6C4675