- name: BE
  description: Backend work
  color: 4395f2
- name: 🧱 BE
  description: Backend work
  color: 4395f2
- name: bug
  description: Something isn't working
  color: ff0000
- name: chore
  description: A non issue related ticket
  color: 3d3937
- name: cooldown
  description: Something to work on between cycles
  color: afc6f2
- name: FE
  description: Frontend work
  color: f9980d
- name: 🌻 FE
  description: Frontend work
  color: f9980d
- name: feature
  description: The fun stuff
  color: c5def5
- name: dependencies
  description: Dependabot pull requests that update a package
  color: 0366d6
- name: 🔥 p1
  description: Highest Priority Bug
  color: e50000
- name: 🤕 p2
  description: Medium Priority Bug
  color: cc0000
- name: 🐌 p3
  description: Low Priority Bug
  color: b20000
- name: 🎨 Design
  description: Design Task
  color: e99695
