name-template: v$NEXT_PATCH_VERSION 🌈
tag-template: v$NEXT_PATCH_VERSION
categories:
  - title: 🚀 Features
    labels:
      - 🎥 feature
      - 🐋 big batch
      - 🦐 small batch
  - title: 🐛 Bug Fixes
    labels:
      - 🐌 p3 bug
      - 🤕 p2 bug
      - 🔥 p1 bug
  - title: 📢 Ad-hoc Work
    labels:
      - 📢 ad-hoc
      - ⌛ hot request
  - title: 🧰 Maintenance
    labels:
      - 🧹 chore
      - 🧊 cooldown
  - title: 📦️ Dependencies
    labels:
      - dependencies
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  ![Smokey](https://github.com/vangst/smokey/workflows/CI%20Smokey/badge.svg)
  
  ## Changes

  $CHANGES
