name: Feature Report
description: Document a new feature request
labels: ["bug"]
body:
  - type: textarea
    id: feature-summary
    attributes:
      label: 📓 Feature Summary
      description: Include a high level, human readable description of the requested feature for public facing release notes.
      placeholder: e.g. Add a calendly input field on candidate profiles.
    validations:
      required: true
 - type: textarea
    id: mvp-requirements
    attributes:
      label: 📔 MVP Acceptance Criteria
      description: List the acceptance criteria required to satisfy the "definition of done".
      placeholder: e.g. I should see a calendly input field when editing my user profile.
    validations:
      required: true
  - type: textarea
    id: questions
    attributes:
      label: 📕 Questions
      description: If there are any remaining questions or grey areas, list those here.
      placeholder: e.g. Do we need to trigger an email for this feature?
  - type: input
    id: figma
    attributes:
      label: 🔗 Figma/Design File
      description: Include a relevant design file.
  - type: textarea
    id: design
    attributes:
      label: 🎨 Design
      description: List any design todos.
      placeholder: e.g. - [ ] Export icons
  - type: textarea
    id: front-end
    attributes:
      label: 🐉 Front-End
      description: List any front-end todos.
  - type: textarea
    id: back-end
    attributes:
      label: 🧜‍♂️ Back-End
      description: List any front-end todos.
  - type: textarea
    id: back-end
    attributes:
      label: 🦺 QA
      description: List ways to kick the tires on this feature before deploying to production.
 
